language: 
    - generic
os:
    - osx
    - linux
before_install:
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
          brew update;
          brew install homebrew/science/mumps --with-openblas --without-mpi;
      fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
          sudo apt-get update;
          sudo apt-get install libblas-dev liblapack-dev libmumps-seq-dev cmake gfortran;
          sudo apt-get install mumps-test;
      fi

install: 
    - pip install virtualenv
    - virtualenv ~/.venv
    - source ~/.venv/bin/activate
    - cp site.template.cfg site.cfg
    - "pip install -q numpy && python setup.py install"
    - pip install pytest
script: py.test tests
